databases:
  - name: ksnbdb
    databaseName: ksnbdb
    user: ksnbdb
    plan: free
    region: ohio

services:
  - type: web
    name: ksnbk
    env: python
    region: ohio
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ksnbdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
