# Generated by Django 4.2.1 on 2023-06-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_blogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blogid',
            field=models.IntegerField(),
        ),
    ]
