# Generated by Django 4.2.1 on 2023-06-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_blogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='imageUrl',
            field=models.TextField(blank=True),
        ),
    ]
