# Generated by Django 4.2.1 on 2023-06-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='recoms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
