# Generated by Django 4.2.1 on 2023-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("upper_no", models.IntegerField()),
                ("depth", models.IntegerField()),
                ("sub", models.IntegerField()),
            ],
            options={"verbose_name_plural": "Categories",},
        ),
    ]
